### PR TITLE
Belindas-closet-android-2-18-fix-compose-compiler-dependency-issue

### PR DESCRIPTION
**Pull request by taylorpapke**
resolves: https://github.com/SeattleColleges/belindas-closet-android/issues/17

### CODE REVIEW

**Comment by taylorpapke** [comment]
Still troubleshooting the issue that this will attempt to fix and any help would be great. Looks like the highest version of the compose compiler is 1.4.8 which is compatible with kotlin version 1.8.22 (but not 1.9.0). Dependabot opened and closed a PR @ https://github.com/SeattleColleges/belindas-closet-android/pull/12 trying to update kotlin version to 1.8.22 before trying to update it to an even higher version (1.9.0) @ https://github.com/SeattleColleges/belindas-closet-android/pull/16. I can't find a version of the compose compiler that works with kotlin version 1.9.0.

**Comment by tinpham5614** [comment]
> Still troubleshooting the issue that this will attempt to fix and any help would be great. Looks like the highest version of the compose compiler is 1.4.8 which is compatible with kotlin version 1.8.22 (but not 1.9.0). Dependabot opened and closed a PR @ #12 trying to update kotlin version to 1.8.22 before trying to update it to an even higher version (1.9.0) @ #16. I can't find a version of the compose compiler that works with kotlin version 1.9.0.

You are right. The highest version Compiler version: 1.4.8 and kotlin version 1.8.22 according to [Compose Compiler Version and Compatible Kotlin Version](https://developer.android.com/jetpack/androidx/releases/compose-kotlin)
For Kotlin version 1.9.0 is 1.5.0 (not yet officially) [Compatibility Table](https://androidx.dev/storage/compose-compiler/repository)

**Comment by taylorpapke** [comment]
Please review if you have time. I am curious to see if this will help solve an issue with the CI failing.

**Review by brandondombrowsky — CHANGES_REQUESTED** [review]
I am not a CI expert as I have only done it once. But I remember we had to tool around a bit and try things to keep the checks from failing. Once we tweaked it in the right way, it worked perfectly. It was just unclear what that perfect tweak was until we tried and failed a few times. So I am happy to approve this to see if it works. We can circle back if we need to try again.

**Review by brandondombrowsky — APPROVED** [review]
I did not mean to request changes. Just a fat fingering mistake on my part :)

**Review by Seiyaroo — APPROVED** [review]
LGTM, Similar sentiments as Brandon, so will approve and merge to sort of "Test the break" as he was implying.

**Pull request merged**
