### PR TITLE
Product functionality added

### LINKED ISSUE #24: Add a product functionality (UI)
As a web/android UI developer, I will want to create the UI for add a product functionality.

**Is your feature request related to a problem? Please describe.**
Users need a user interface to add products to their inventory.

**Describe the solution you'd like**
Create a user interface for adding a product. 

**Story Points**
4-10

### PR DESCRIPTION
**Pull request by Robel-003**
Resolve #24 

- Implemented product functionality to add products based on product name, description, and size. Can add more fields if necessary. 
- From login page, user can navigate to add product page to add a product. Ideally, once user logins in, the add product should appear instead of it showing on login page.
- User can input product details but currently unable to save product to an inventory or database

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
Looks great! Only thing I noticed was that 2nd and 3rd fields were both labeled "product description" and I thought you had intended for one of them to be labeled "size". A 'back' or 'home' button would also be nice in the meantime for testing purposes. These are minor and could always be added in future iterations. I am curious of what your opinion is but I think we should move in the direction of a drop box for selecting size. The Belinda's Closet Submission Form currently takes a preset size selection vs. a user inputed value and it may be a good idea to stick with that format.

**Comment by brinkbrink** [comment]
Thanks, Robel! Merging now but of course, just take note of the suggestions above (I will do the same and may create an issue to fix them in the future or if you have time before tomorrow's meeting you can do the same if you feel comfortable). Also, would love to see some screenshots included for UI pull requests in the future but no worries for this one.

**Comment by Robel-003** [comment]
Thanks for the feedback! Those are some good notes and add ons for sure. I'll be sure to fix those things and add those additional components.

**Comment by brinkbrink** [comment]
@Robel-003 just remember to create an issue for yourself or let me know if you'd like for me to create the issue!

**Comment by Robel-003** [comment]
> Looks great! Only thing I noticed was that 2nd and 3rd fields were both labeled "product description" and I thought you had intended for one of them to be labeled "size". A 'back' or 'home' button would also be nice in the meantime for testing purposes. These are minor and could always be added in future iterations. I am curious of what your opinion is but I think we should move in the direction of a drop box for selecting size. The Belinda's Closet Submission Form currently takes a preset size selection vs. a user inputed value and it may be a good idea to stick with that format.

> I had to go back and check Belinda's closet submission form and I agree, a drop down list of some sort would be better to select sizes

**Pull request merged**
