### PR TITLE
belindas-android_03_194_navigation-update-pages

### PR DESCRIPTION
**Pull request by Annelisebx**
**Resolves[ Issue 194](https://github.com/SeattleColleges/belindas-closet-android/issues/194) and User Story [74](https://github.com/SeattleColleges/belindas-closet-android/issues/74)**

**completed:**
- Hamburger added to Update.kt
- Hamburger added to IndividualProductUpdate.kt
image
image

As a user I want to be able to navigate between pages when on the pages to update my items.

**Is your feature request related to a problem? Please describe.**\
Navigation bar needs to be consistent across all pages on the app.

**Describe the solution you'd like**\
Add navigation bar and icons to all pages where applicable.

**Is this issue related to any other issues?**\
[Issue 188](https://github.com/SeattleColleges/belindas-closet-android/pull/188) - add to 'Get Started pages' by 
@MuhammadNSC 
[User Story 74](https://github.com/SeattleColleges/belindas-closet-android/issues/74): NAVIGATION

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
Tested this and both update pages have hamburger menu added. Thanks for doing this!

**Review by tinpham5614 — APPROVED** [review]
LGTM

**Comment by Annelisebx** [comment]
Removed all commits after original since they were not signed.

**Comment by Annelisebx** [comment]
Closing. New [PR 202](https://github.com/SeattleColleges/belindas-closet-android/pull/202) with new commits. Resolves same issue.

**Pull request closed without merging**
