### PR TITLE
Create dependabot.yml

### PR DESCRIPTION
**Pull request by taylorpapke**
Enabled dependabot on repo and added yaml file to check gradle dependencies daily.

### CODE REVIEW

**Review by theGaryLarson — APPROVED** [review]
Seems how this is the standard dependabot.yml with no additional config. I'd change the interval to weekly for now just so there isn't additional PR and reports to look through. Once we have it targeted specifically for best use in this project then consider if it needs to run daily or not.

**Review by brandondombrowsky — DISMISSED** [review]
I echo Gary's comments. Once we have more awareness on how often dependencies change will influence how often we really need it to be.

**Review by brinkbrink — APPROVED** [review]
Thanks for making that change. Looks good to me!

**Review by bcko — APPROVED** [review]
Looks good to me.

**Pull request merged**
