### PR TITLE
Belindas_android-100-add_product_page-01

### LINKED ISSUE #100: Change enum and variable names to match new names
**Describe the bug**\
New names were created for enums and variables which is inhibiting code from compiling on a new PR request with the new names. In order to merge new code to main the names in the main codebase need to be changed to the new names.

Please edit this issue and add those new names here:

- [ ] old name _need to change to_ new name
- [ ] old name _need to change to_ new name
- [ ] old name _need to change to_ new name
- [ ] old name _need to change to_ new name

**To Reproduce**\
1. Go to PR #87 
2. Scroll down to where the merge button is and notice that there is a merge conflict. 
3. Read Gary's latest comment on the PR for more context.

**Expected behavior**\
This PR #87 will be able to be merged to main without this conflict.

**Is this issue related to any other issues?**\
The PR #87 is related to Issue #71 

**Additional context**\
@taylorpapke or @Robel-003 please edit this issue to include the new names.

**Story Points**\
1-2

### PR DESCRIPTION
**Pull request by Robel-003**
Resolves #100 

Updated variable names in AddProduct page for different product types.

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
The names have been changed correctly and everything seems to be working properly now:
Screenshot 2023-11-01 at 2 17 36 AM

**Comment by tinpham5614** [comment]
As per the screenshot that Taylor posted, I think we need more fields such as:

1. productGender, 
2. productSizeShoe/productSizes, 
3. productSizePantsWaist, 
4. productSizePantsInseam, 
5. productImage.

Is there an issue related to this that I may have overlooked?

**Comment by taylorpapke** [comment]
@tinpham5614 I think this was just a fix to resolves some naming conflicts. I think @robel will have to make another issue and PR to add the remaining fields at some point to complete the user story.

**Comment by tinpham5614** [comment]
@taylorpapke thank you.

**Review by tinpham5614 — APPROVED** [review]

**Pull request merged**
