### PR TITLE
Belinda_Android_Sprint_2_187_Navbar_ForgotPassword_Page 

### PR DESCRIPTION
**Pull request by MuhammadNSC**
This Issue is related to user story #74.
I've added the menu icon to the forgotPasswordPage page.

Screenshot 2023-11-23 at 1 47 03 PM

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
Looks great! Hamburger icon is shown and does not crash app.

**Review by Robel-003 — APPROVED** [review]
LGTM! hamburger icon is working

**Review by Annelisebx — APPROVED** [review]
Navigation bar works, thanks for adding to these pages.

**Comment by taylorpapke** [comment]
@MuhammadNSC It looks like #190 had this PR included in it. There are no changes to merge on this PR so I will close it.

**Pull request closed without merging**
