### PR TITLE
Hotfix_to_main_October_17

### PR DESCRIPTION
**Pull request by nickolasram**
a few curly braces were missing in two files. Compiles again.

### CODE REVIEW

**Comment by brinkbrink** [comment]
resolves #79

**Review by brinkbrink — CHANGES_REQUESTED** [review]
So close! I'm hitting unresolved reference errors on [IndividualProductUpdate.kt](https://github.com/SeattleColleges/belindas-closet-android/blob/main/app/src/main/java/com/example/belindas_closet/screen/IndividualProductUpdate.kt)

It's ConfirmSaveDialog and ConfirmationDialog on lines 164 and 185, respectively. You just need to instantiate those composable functions (like what you did in lines 217+) for those composables. Lmk if that doesn't make sense.

**Comment by brinkbrink** [comment]
So basically you just need to do what you did in lines 217+ for those composables.

**Comment by nickolasram** [comment]
Okay, I see. Weird how my IDE isn't flagging that error, but I understand why that's happening and what's going on.

**Review by brinkbrink — APPROVED** [review]

**Pull request merged**
