### PR TITLE
belinda-android-05-267-add-change-password-function

### LINKED ISSUE #267: Change Password Page: Add change password function
As a developer, I want to add a change password function to the change password page.
1. Edit the page name from Reset Password Page to Change Password Page
2. Add a current password field
3. Utilize the change password API endpoint
4. Create a function for the change password button

### PR DESCRIPTION
**Pull request by tinpham5614**
Resolves #267 

This PR will refactor the current code from reset password to change password. This also included the change password function that allows users to change their password as needed.

**Demo:**
**Successful**

[Screencast from 2024-04-17 22-27-56.webm](https://github.com/SeattleColleges/belindas-closet-android/assets/72054441/d416c9d6-3c92-45a1-b92e-ed053b359ad5)

**Error: Wrong current password**

[Screencast from 2024-04-17 22-26-24.webm](https://github.com/SeattleColleges/belindas-closet-android/assets/72054441/e85feb7a-a2f4-44ee-b6cf-cdb3cb85c109)

**Error: New password is the same as the previous password**

[Screencast from 2024-04-17 20-56-52.webm](https://github.com/SeattleColleges/belindas-closet-android/assets/72054441/89c013f8-f259-4670-8a83-7edcde5fc3ac)

**Other Errors**

[Screencast from 2024-04-17 20-51-08.webm](https://github.com/SeattleColleges/belindas-closet-android/assets/72054441/88d4da61-b705-44d9-bd71-1c5079e71e67)

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
This is working fine on my end. I was able to replicate all of the successes and errors from the videos you posted. @MaddasaHatter

**Comment by heosman** [comment]
@tinpham5614 How exactly do I get to the Change password page? When I put in my email on the Forgot Password page, I get an Invalid Email error but I still get a temporary password. Logging in just routes me to the Home page though.

**Comment by tinpham5614** [comment]
@heosman I change the landing page to ChangePassword page in the ScreenMain file as the screenshot

image

**Review by heosman — APPROVED** [review]
I was able to change my password successfully and also replicate the errors.

**Pull request merged**
