### PR TITLE
belinda_android-enhancement-118-forgot_password_function

### LINKED ISSUE #118: Feature: Add forgot password function - reset token
As a developer, I want to implement a forgot password feature that allows users to reset their password by generating a new token.

1. Create dtos (request + response)
2. Create a service that will call the forgot password API from the backend.
3. Add the resetToken function to the button.

Currently, we are using the log to print the new token. We will decide on other solutions such as sending a new token (password) via email or phone number.
- Email with Nodemailer in NestJS

### PR DESCRIPTION
**Pull request by tinpham5614**
Resolves #118 

1. Create forgot password dtos (request + response)
2. Create a service that will call the forgot password API from the backend.
3. Add the resetToken function to the button.

_Note:_ Currently, we are using the log to print the new token. We will decide on other solutions such as sending a new token (password) via email or phone number:
- Email with Nodemailer

### Successful reset token with valid Email
success

### Logcat
logcat

### Failed reset token with invalid Email
failed

### CODE REVIEW

**Review by Seiyaroo — APPROVED** [review]
Contextually, it looks good to me, and if its working i'd say its good. That said I don't know enough about loggers and the moving parts here to affirm my approval. Would love to get a 1:1 walkthrough sometime haha.

**Review by taylorpapke — APPROVED** [review]
Tested this and it is working as expected. I will also mention for anyone wanting to test that this requires running the backend at the same time and having a valid user with an email in your mongoDB database:
Screenshot 2023-11-05 at 2 37 26 PM
Screenshot 2023-11-05 at 2 38 23 PM
Screenshot 2023-11-05 at 2 38 55 PM

**Comment by taylorpapke** [comment]
@tinpham5614 @Robel-003 I think we need to update the branch. Will this run the check properly once updated?

**Comment by tinpham5614** [comment]
@taylorpapke 
I still get an error after updating "Required statuses must pass before merging".
I will test by closing and reopening the PR to trigger the checks.

**Pull request merged**
