### PR TITLE
Spring2024

### PR DESCRIPTION
**Pull request by ogarmela**

### CODE REVIEW

**Review by Seiyaroo — APPROVED** [review]
Looks good. In the future we can split these into two different PR's probably on something that might be larger. :) Also if we can try to keep the names consistent. 

<Repo><Goal of pull request> is usually how we've done it but I can try to find the more specific guideline in our wiki somewhere.

**Comment by taylorpapke** [comment]
@brinkbrink @Seiyaroo This is a good example to help determine what approach we should take in dealing with ESLint errors. If it is not critical, should we bypass and allow to be merged. My only concern is that it appears some of the tests were not run after the lint failed:
Screenshot 2024-04-16 at 12 15 24 PM

It also appears that this repo is allowing for 1 approval to merge which is not the case for all our other repos.

**Comment by Seiyaroo** [comment]
Yeah @taylorpapke I didn't want to squash and merge due to the 1 approval review thing. It puzzled me. As for the tests not running that coulda been me? I chose to only run failed tests this morning rather than all tests. After this post I will attempt a run of all tests and see what happens.

**Comment by tinpham5614** [comment]
Is this a pull request?
I'm not sure if this was created by the author who was getting familiar with the code base.

**Comment by brinkbrink** [comment]
Looking at the commit history there are only other folks' commits, I'm pretty sure. Kinda braindead right now after attending sessions/talking to strangers all day, though.

**Comment by tinpham5614** [comment]
@brinkbrink Should we close this for now since this is not a PR to solve any issue?

**Comment by brinkbrink** [comment]
Yeah, @tinpham5614, I'll close it out with this comment. 

@ogarmela Please reference [this page](https://github.com/SeattleColleges/belindas-closet/wiki/Development#git-branch-naming-convention) from our wiki about our git branch naming convention. Read more about GitHub branches in general [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-branches). We create a branch for every change we want to create in the existing code base and then create a pull request when we're ready for that branch with the change to be reviewed. Then when you make a new change you create a new branch. Does that make sense? Reach out to me or @tinpham5614 on Slack if you need more detail. This is something we can also talk about this Thursday.

**Pull request closed without merging**
