### PR TITLE
belindas-closet-android_2_241_navbar-login-button

### LINKED ISSUE #241: HOME PAGE: Remove buttons & add 'Login' button to Navbar
Relates to #243 

As a developer, I will want to remove the 'Get Started' & 'Add Product' button from the home page and add a "Login" button to the Navbar (TopBar).

**Tasks**
- [x] - Remove 'Get Started' & 'Add Product' buttons from Home Page
- [x] - Add 'Login' button to the Navbar

### PR DESCRIPTION
**Pull request by cshimm**
Removed "Get Started" and "Add Product" button from homepage and added Login button to Navbar. It is the same style button used for the NSC Events android app.

resolves #241

### CODE REVIEW

**Comment by taylorpapke** [comment]
@cshimm Please open this up against the main branch (not staging). @bcko This brings up a good point about branch protection. Should we block merging to staging and production for all repos? Would this be lock branch in the settings?

**Comment by bcko** [comment]
> @cshimm Please open this up against the main branch (not staging). @bcko This brings up a good point about branch protection. Should we block merging to staging and production for all repos? Would this be lock branch in the settings?

Updated the pull request so `main` is the branch that this pull request is merging to. 
@taylorpapke let me look into branch protection settings.

**Comment by bcko** [comment]
@taylorpapke 

branch protection ruleset is added for `main` `staging` `production` for this repo. I will add the same ruleset to other repos.

image

**Review by bcko — APPROVED** [review]
@cshimm great job.

**Review by taylorpapke — APPROVED** [review]
Awesome job! Looks great.

**Pull request merged**
