### PR TITLE
belindas-closet-android_1_46_create-a-registration-page

### LINKED ISSUE #46: UI - Create a Registration Page
As a developer, I would like to be able to have a registration page that will allow users to sign up for the application. 

**Describe the solution you'd like**
We need a basic Registration page that will have an associated form. Information on that form will be potentially:

**First Name:** Nick
**Last Name:** Di Pietro
**Email Address:** FName.LName@seattlecolleges.edu 

_Make sure you take note that names will be strings and email address can be .edu, .com, .org, or any of the normally associated endings. Be sure to use type safety to avoid any potential bugs that arise from a client inputting incorrect information._

**Helpful Tutorials/Resources**

[Jetpack Compose Tutorial](https://developer.android.com/jetpack/compose/tutorial)
[Geeks for Geeks on buttons in Kotlin](https://www.geeksforgeeks.org/button-in-kotlin/)
[Medium article on Routes in Android Studio](https://medium.com/swlh/navigate-between-activities-in-android-studio-c7f4617e7388)

**Story Points**
6-12

### PR DESCRIPTION
**Pull request by heosman**
Resolves #46 

This PR will add a sign up form on the registration page so users can create an account for the application.

registration page

### CODE REVIEW

**Review by Robel-003 — APPROVED** [review]
Looks good! I'm able to enter text into the fields and email field forces you to enter a proper email. Great job!

**Comment by tinpham5614** [comment]
Should users be asked to provide a password and confirm it on this signup page?
Example:
Password: ____________
Confirm password: ____________

**Review by theGaryLarson — APPROVED** [review]
Everything works as expected. Good job!

**Comment by theGaryLarson** [comment]
I approved but agree with @tinpham5614 there needs to be password confirmation added to this page. It can be opened as another issue though.

**Comment by heosman** [comment]
> Should users be asked to provide a password and confirm it on this signup page? Example: Password: ____________ Confirm password: ____________

@tinpham5614 @theGaryLarson I noticed that in the [Belinda's Closet Mobile App Layout](https://github.com/SeattleColleges/belindas-closet-android/wiki/Belinda's-Closet-Android-Wiki#belindas-closet-mobile-app-layout) diagram, the sign up form is supposed to also prompt for a username and password, but this wasn't mentioned in the original issue for this pull request. If another issue is created for this, I would definitely like to work on that!

**Pull request merged**
