### PR TITLE
belindas_closet_android_4_142_add_appropriate_mit_licensing-to-each_repository

### PR DESCRIPTION
**Pull request by brandondombrowsky**
This will add the appropriate licensing to our body of work and relates to User Story 142 within belindas-closet-android.

Relates to: #205

### CODE REVIEW

**Review by bcko — APPROVED** [review]

**Review by taylorpapke — APPROVED** [review]
I read through this and didn't see any errors or typos.

**Comment by brandondombrowsky** [comment]
@taylorpapke Do you know why it isn't passing one of the checks? I am a little unsure what to fix or if I simply need to "Merge without waiting for requirements to be met (bypass branch protections)"

**Comment by brinkbrink** [comment]
@brandondombrowsky Try clicking the "Update branch" button. Also, I've learned from troubleshooting this in the past that sometimes the checks get hung up and you just need to trigger them again (which I think will happen if you click that button).

**Comment by brandondombrowsky** [comment]
@brinkbrink I am still getting one unresolved check... And in fact, other than awaiting a few approvals, both of the problems I am having are in the android repos for each client. All the other repos passed all checks without incident... 
image

**Comment by taylorpapke** [comment]
@brandondombrowsky I believe this is due to the CI not registering on pull request for this file type. @Robel-003 should we add .md to the on-pull-request yaml?
Screenshot 2023-11-28 at 1 50 59 PM

**Comment by taylorpapke** [comment]
Hey @brandondombrowsky I added the following to https://github.com/SeattleColleges/nsc-events-android/pull/164/files and the same should apply here:
Screenshot 2023-11-29 at 3 20 43 PM
Just add that line of code to the on-pull-request.yml and it should run and pass CI so we can get this merged.

**Pull request merged**
