### PR TITLE
belinda-android_02_133_display-new-product

### LINKED ISSUE #133: Display new product just added.
As a developer, I want to display the newly added product below the Add Product button. 
This will inform users of the product details and allow them to make changes if necessary.

### PR DESCRIPTION
**Pull request by tinpham5614**
Resolves #133 
This PR will display a new product just added below the Add Product button, which will inform users of the product details and allow them to make changes if necessary.

1. Add a DisplayNewProduct composable function
2. Modified productType in newProduct to get change when user select from the drop down
3. Display a new product details when new product input not empty.
image
4. If the new product type is Shoes, it will display shoe size.
image
5. If the new product type is pants, it will display pants waist and pants inseam sizes
image

### CODE REVIEW

**Review by taylorpapke — DISMISSED** [review]
Pretty cool! The screenshots helped me to see the differences when shoes and pants were selected vs. everything else. Works as expected.

**Review by Robel-003 — DISMISSED** [review]
This definitely helps ensure the user entered the correct information. Tested it out locally and it's working as expected. Thanks for the screenshot, it really helps

**Review by CourtneyHoppus — DISMISSED** [review]
I was able to see the difference in the product based on category.
I think next the add product screen needs to also update dynamically when you select the category, so that you can input those category specific properties.

**Comment by taylorpapke** [comment]
@tinpham5614 just a conflict to fix here and it's ready to go

**Review by taylorpapke — APPROVED** [review]

**Review by brinkbrink — APPROVED** [review]
Thank you for resolving the conflict!

**Pull request merged**
