### PR TITLE
belindas-closet-android_5_271_add-profile-dropdown

### LINKED ISSUE #271: Nav Bar: Create profile dropdown
As a user, I will want to navigate to the dashboard page and be able to sign out using the nav bar.

- [ ] Create a profile dropdown that will contain links to the dashboard and sign out.

Relates to #270

### PR DESCRIPTION
**Pull request by heosman**
Resolves #271 

This PR adds a profile dropdown to every page (except the Sign Up, Login, Forgot Password, and ResetPassword pages). On pages other than the AdminView, CreatorView, Add Product, and Edit User Role pages, I added role-based access to the profile dropdown so that only users signed in as admin and creators would be able to see the profile dropdown. Pressing the profile dropdown opens a dropdown menu with a dashboard link and sign out link. The dashboard link is currently not functioning. Below are some screenshots of some of the pages.

Home page (not logged in as admin or creator):
home page not logged in

Home page (logged in as admin or creator):
home page logged in as admin

Admin page:
adminview page

Product Detail page:
productdetail page

Related to #270

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
Looks great! The dropdown works for me on all of the pages you mentioned while logged in as a creator/admin. A couple things I noticed which are unrelated to this PR is that the add product page is not available in both admin and creator pages. Also, the dashboard button on the dropdown crashes the app.

**Comment by heosman** [comment]
> Looks great! The dropdown works for me on all of the pages you mentioned while logged in as a creator/admin. A couple things I noticed which are unrelated to this PR is that the add product page is not available in both admin and creator pages. Also, the dashboard button on the dropdown crashes the app.

@taylorpapke I also noticed that the Add Product can't be accessed without changing ScreenMain to open to that page. The dashboard page is probably crashing because the dashboard page doesn't exist yet.

**Review by Robel-003 — APPROVED** [review]
This looks great! Once I logged in as an admin or creator, I was able to view the dropdown menu in all the pages you specified. Like you stated, the dashboard link isn't functional but I was able to sign-out with the sign-out link.

**Review by intisarosman1 — APPROVED** [review]
When logged in as a creator, I can see the profile dropdown when I press the profile icon. LGTM 
Screenshot 2024-04-23 213213

**Pull request merged**
