### PR TITLE
belinda_android-add_login_functionality-01

### PR DESCRIPTION
**Pull request by tinpham5614**
Solves #98 
This is related to #99  and I will close it.
This PR will add the login functionality to the login button which currently is non-functional.

Describe the solution you'd like
1. Create Login Service to request and get a response (token) from the backend
2. Store the token in the Android's SharePreferences.
3. Create Toast message to inform users about the success or failure of login.

To test the login function you will need to run the backend as well [backend](https://github.com/SeattleColleges/belindas-closet-nestjs)

Demo:
[Video](https://github.com/SeattleColleges/belindas-closet-android/assets/72054441/70f54993-e893-4fa7-9882-93088a2bd6b6)

### CODE REVIEW

**Comment by taylorpapke** [comment]
How do I create a password so I can log in?

**Comment by Robel-003** [comment]
hey @tinpham5614, I'm probably missing something but I get an invalid password and email toast message when trying to log in. Got the backend running. Would I need to create an account first?

**Comment by tinpham5614** [comment]
> @tinpham5614 How do I create a password so I can log in?

You can use sign up endpoint to sign up first: http://localhost:3000/api/auth/signup/
Json example for sign up:
```
{
    "name": "John",
    "email": "john@gmail.com",
    "password": "john123",
    "role": "admin"
}
```
And then, use email and password to log in.

**Comment by tinpham5614** [comment]
> hey @tinpham5614, I'm probably missing something but I get an invalid password and email toast message when trying to log in. Got the backend running. Would I need to create an account first?

Yes, you need to create an account and log in. Use the sign-up endpoint mentioned above.

**Comment by taylorpapke** [comment]
Ok, I am still getting the invalid username or password toast message (wasn't able to capture in this screenshot):
Screenshot 2023-11-01 at 1 51 35 PM
and this is what I'm getting in the nestJS terminal:
Screenshot 2023-11-01 at 1 50 04 PM

**Comment by tinpham5614** [comment]
my .env looks like this:
```
MONGODB_URI=<connection string>
NEXTAUTH_URL=http://localhost:3000
NEXTAUTH_SECRET=secret
JWT_SECRET=secret
JWT_EXPIRES="1d"
PRODUCT_KEY=secret
```

**Comment by taylorpapke** [comment]
> Can you check if the backend code is up-to-date? my .env looks like this:
> 
> ```
> MONGODB_URI=<connection string>
> NEXTAUTH_URL=http://localhost:3000
> NEXTAUTH_SECRET=secret
> JWT_SECRET=secret
> JWT_EXPIRES="1d"
> PRODUCT_KEY=secret
> ```

Yes, I needed to add the JWT_EXPIRES="1d" line to my .env. I am able to log in and it takes me to the add product page!

**Review by taylorpapke — APPROVED** [review]

**Review by Robel-003 — APPROVED** [review]
got it, I was able to signup with that endpoint and sign in routing me to the product page.

**Pull request merged**
