### PR TITLE
belinda_android-02-84-refactor_product_model

### LINKED ISSUE #84: Refactor Product Model
**Make sure the first line is formatted as follows.**\
As a developer, I will want to refactor the Product Model to match the backend Product Model.

**Is your feature request related to a problem? Please describe.**\
Currently, the product model is incomplete. It will be completed if we add more fields as the form below
[Product Submission Google Form](https://docs.google.com/forms/d/1XPgVM7mwK1aQG22SUxl__56sbnxf9F-I3PWNfRq7zmQ/viewform?edit_requested=true)
**Describe the solution you'd like**\
My solution is to add more fields to the product model.

**Describe alternatives you've considered**\
Using enum class as Size class already created.

**Is this issue related to any other issues?**\
Issue related to #72 

**Story Points**\
4-6

### PR DESCRIPTION
**Pull request by tinpham5614**
Resolves #84 

This PR will update the product model to match with the backend. Below is the submission form:
[Submission Form](https://docs.google.com/forms/d/1XPgVM7mwK1aQG22SUxl__56sbnxf9F-I3PWNfRq7zmQ/viewform?edit_requested=true)

- Added more enum classes to create a new product with the drop-down menu (similar to the Sizes previously)
- Updated other screens to make the app work properly.
- Shoe sizes are displayed numerically, while waist and inseam sizes are shown for pants.

Screenshot 2023-10-19 174035
Screenshot 2023-10-19 174307

### CODE REVIEW

**Comment by nickolasram** [comment]
I have a couple questions:

Is the ProductType supposed to represent the name of the product or the larger category the product falls under? With ProductType being an ENUM and no separate ProductName field every product within a category is going to be called the same thing as things are now.

Since the products are supposed to be separated into larger categories (dresses, shirts, etc.), how are we going to store a list of our categories (along with whatever images we'll use to represent them on the home page)? Shouldn't we be creating a Category/Type model as well?

**Comment by tinpham5614** [comment]
Hi @taylorpapke, do you have any ideas on this?

**Comment by taylorpapke** [comment]
Hi @nickolasram @tinpham5614 Yes, I suppose we will need a category type as well. I still need to talk to the client about what kind of categories they would like. For now, I think the category type should be the same as the product type and we could potentially remove the product type name: "dress" from each of the product cards and place it at the top under the nav bar to show we are on the dresses page. 
We may be able to hold off on this for now because the client may want a "graduation" or "winter" category in which case it will be useful to have the product type name: "gown (graduation)" or name: "jacket/blazer" on each card that is shown on the product page for that category. @theGaryLarson will we need to change our model to facilitate this?

**Comment by tinpham5614** [comment]
@taylorpapke thank you for the clarification.

**Review by taylorpapke — APPROVED** [review]
I think we should merge this in and work on any further updates from a new issue and PR

**Review by brinkbrink — APPROVED** [review]
Sounds good, @taylorpapke, merging now.

**Pull request merged**
