### PR TITLE
Update on-pull-request.yml

### PR DESCRIPTION
**Pull request by Robel-003**
updating ci workflow to trigger on new commits made on open pr's

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
I read the [discussion](https://github.com/orgs/community/discussions/25161) @Robel-003 messaged me and I think this is worth a shot!

**Comment by taylorpapke** [comment]
@Robel-003 Hey, what happened to the proposed changes for this one? New info?

**Comment by Robel-003** [comment]
> Hey @Robel-003, what happened to the proposed changes for this one? New info?

@taylorpapke What I added in the pull-request.yml file didn't trigger the workflow. I changed some styling in one of the pages and committed the changes, but it didn't trigger the workflow. Researching right now to find another fix

**Comment by Robel-003** [comment]
This pr has been resolved by a recent pr push to main.

**Pull request closed without merging**
