### PR TITLE
Belinda_Android_Sprint_2_xx_individual_product_page_and_delete

### PR DESCRIPTION
**Pull request by nickolasram**
It may say this branch is behind main, but I've updated it to include all the updates from Muhammad's delete-add-product-button branch and the latest update to main.

Adds an individual product page and deletion as Taylor described on Slack.

[Here's a video demoing my changes](https://youtu.be/jyKALhOOWhQ)

### CODE REVIEW

**Review by taylorpapke — CHANGES_REQUESTED** [review]
Looks great but let's resolve the merge conflicts.

Here's a helpful doc for that:
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github

**Comment by nickolasram** [comment]
> Looks great but let's resolve the merge conflicts.
> 
> Here's a helpful doc for that: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github

Conflicts Resolved

**Review by brinkbrink — APPROVED** [review]

**Comment by brinkbrink** [comment]
This is where the bug @MuhammadNSC is originating. In the Update.kt file. Can you look into this @nickolasram ? I will check back in later this week to see how it's going and support if needed. Looks like something buggy cropped up when resolving the merge conflict. My bad for not looking at this closer before force-merging. Thanks for bringing this up, Muhammad!

**Comment by nickolasram** [comment]
> This is where the bug @MuhammadNSC [found](https://nscad.slack.com/archives/C05URJZMCVB/p1697599489973399) is originating. In the Update.kt file. Can you look into this @nickolasram ? I will check back in later this week to see how it's going and support if needed. Looks like something buggy cropped up when resolving the merge conflict. I should've looked at this closer before force-merging. Lesson learned. Thanks for bringing this up, Muhammad!

Bugs should be fixed. Hotfix branch pushed and pull request created

**Pull request merged**
