### PR TITLE
belindas-closet_sprint01_issue43_forgot-password

### PR DESCRIPTION
**Pull request by Annelisebx**
**Resolves [Issue 43](https://github.com/SeattleColleges/belindas-closet-android/issues/43)**

**As a developer, I did the following:** 
- Created a new screen for when a user forgets their password and clicks on text 'Forgot Password' from login screen
- The user can enter their email address and press submit
- The user can press the 'back arrow' to return to the Login screen

**See Image of 'Forgot Password' screen below:** 
image

*We also want to include unit tests if and when possible to make sure we're getting full coverage of our code. This will simulate a real world environment where tests are extremely important.**
**--No Tests Yet--**

[Unit Test Example](https://www.geeksforgeeks.org/unit-testing-software-testing/)

### CODE REVIEW

**Comment by Annelisebx** [comment]
I need help creating a test for this PR. I am unsure what one would look like in this scenario.

**Review by taylorpapke — APPROVED** [review]
Looks great! 
Here is a few links I found helpful in regards to Jetpack Compose UI testing:
Navigation testing video- https://www.youtube.com/watch?v=ThVzTZVKXLY
Android Developers doc: https://developer.android.com/jetpack/compose/testing

**Comment by tinpham5614** [comment]
Just a minor thing:
When clicking the back arrow from the Forgot Password Page, it should return to the Login Page instead of the Home Page.
Great work

**Comment by Annelisebx** [comment]
> Just a minor thing: When clicking the back arrow from the Forgot Password Page, it should return to the Login Page instead of the Home Page. Great work

@tinpham5614 
I just updated the route of the back arrow to return to Login and not Home. Thank you for catching!

**Pull request merged**
