### PR TITLE
Belindas_android-Enhancement-83-distinct_category_pages

### PR DESCRIPTION
**Pull request by nickolasram**
This branch branches off belindas_closet-01-100-update_var_names (the latest open pull request.)
Resolves bug #81
Resolves bug #89
Adds enhancement #83

- Now allows us to remember the productType we want as we navigate to and from pages (MainActivity.js)
- filters out products that aren't part of the type we want (ProductDetail.js & Update.js)
- **All product types on the home page are currently using the same placeholder image** (Home.js)
- **Some types don't have any products associated with them. Will produce empty product pages.**
- _the types are currently ordered alphabetically on the main page. We can consider better sorting later_ (Home.js)

### CODE REVIEW

**Comment by taylorpapke** [comment]
I tested this out and it appears that it works as expected. I see 2 dresses in the dress category and nothing in any of the other categories which makes sense. Looks like we are just using the dress image for all categories but that can be easily changed.

**Review by taylorpapke — APPROVED** [review]

**Comment by tinpham5614** [comment]
A few conflicts need to be resolved in the AddProduct Page.

**Comment by nickolasram** [comment]
> A few conflicts need to be resolved in the AddProduct Page.

conflicts should be resolved now

**Comment by taylorpapke** [comment]
Awesome! I tested this and see that it is now placing the different products in their respective categories. Nice work!

**Review by taylorpapke — APPROVED** [review]

**Review by tinpham5614 — APPROVED** [review]
LGTM

**Pull request merged**
